In [1]:
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json


con = sqlite3.connect("db.sqlite3")
df = pd.read_sql_query("select DATE,RF from weather_data",con)
con.close()
df = df.copy()

In [2]:
print(df)

                     date   RF
0     1993-01-01 00:00:00  0.0
1     1993-01-02 00:00:00  0.0
2     1993-01-03 00:00:00  0.0
3     1993-01-04 00:00:00  0.0
4     1993-01-05 00:00:00  0.0
5     1993-01-06 00:00:00  0.0
6     1993-01-07 00:00:00  0.0
7     1993-01-08 00:00:00  0.0
8     1993-01-09 00:00:00  0.0
9     1993-01-10 00:00:00  0.0
10    1993-01-11 00:00:00  0.0
11    1993-01-12 00:00:00  0.0
12    1993-01-13 00:00:00  0.0
13    1993-01-14 00:00:00  0.0
14    1993-01-15 00:00:00  0.0
15    1993-01-16 00:00:00  0.0
16    1993-01-17 00:00:00  0.0
17    1993-01-18 00:00:00  0.0
18    1993-01-19 00:00:00  0.0
19    1993-01-20 00:00:00  0.0
20    1993-01-21 00:00:00  0.0
21    1993-01-22 00:00:00  0.0
22    1993-01-23 00:00:00  0.0
23    1993-01-24 00:00:00  0.0
24    1993-01-25 00:00:00  0.0
25    1993-01-26 00:00:00  0.0
26    1993-01-27 00:00:00  0.0
27    1993-01-28 00:00:00  0.0
28    1993-01-29 00:00:00  0.0
29    1993-01-30 00:00:00  0.0
...                   ...  ...
6544  2007-12-02 00:00:00  0.0
6545  2007-12-03 00:00:00  0.0
6546  2007-12-04 00:00:00  0.0
6547  2007-12-05 00:00:00  0.0
6548  2007-12-06 00:00:00  0.0
6549  2007-12-07 00:00:00  0.0
6550  2007-12-08 00:00:00  0.0
6551  2007-12-09 00:00:00  0.0
6552  2007-12-10 00:00:00  0.0
6553  2007-12-11 00:00:00  0.0
6554  2007-12-12 00:00:00  0.0
6555  2007-12-13 00:00:00  0.0
6556  2007-12-14 00:00:00  0.0
6557  2007-12-15 00:00:00  0.0
6558  2007-12-16 00:00:00  0.0
6559  2007-12-17 00:00:00  0.0
6560  2007-12-18 00:00:00  0.0
6561  2007-12-19 00:00:00  0.0
6562  2007-12-20 00:00:00  0.0
6563  2007-12-21 00:00:00  0.0
6564  2007-12-22 00:00:00  0.0
6565  2007-12-23 00:00:00  0.0
6566  2007-12-24 00:00:00  0.0
6567  2007-12-25 00:00:00  0.0
6568  2007-12-26 00:00:00  0.0
6569  2007-12-27 00:00:00  0.0
6570  2007-12-28 00:00:00  0.0
6571  2007-12-29 00:00:00  0.0
6572  2007-12-30 00:00:00  0.0
6573  2007-12-31 00:00:00  0.0

[6574 rows x 2 columns]